FROM python:3.10-slim

WORKDIR /usr/src/app


COPY requirements.txt /usr/src/app

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["gunicorn", "-c", "/usr/src/app/api/configuration/gunicorn_conf.py", "wsgi:application"]
